### PR TITLE
Update resource def

### PR DESCRIPTION
**Pull request by arnoldna**
Added Virtual Hub naming regex

### CODE REVIEW

**Comment by Nepomuceno** [comment]
According to git you are changing all the files it is probably because you have a different line ending. Might be work looking into that.

**Comment by Nepomuceno** [comment]
You need to run 'go generate' after you added the definition them it will update the required files for you after that I recommend running 'go test ./...' To check if all the tests are still working

**Review by Nepomuceno — APPROVED** [review]

**Comment by Nepomuceno** [comment]
Elready fixed by other PR

**Comment by arnaudlh** [comment]
Closing as the change is included in #72 - thanks @arnoldna for your contribution

**Pull request closed without merging**
