### PR TITLE
Enhancement / Issue #102 

### PR DESCRIPTION
**Pull request by schoenr79**
Add following definitions:
- azurerm_storage_sync
- azurerm_storage_sync_group

Additions:
Improve makefile / _make_ is now able to display a help

### CODE REVIEW

**Comment by schoenr79** [comment]
Created the PR @arnaudlh but there is one conflict in the models_generated.go file. is this up to me to fix this?

**Comment by arnaudlh** [comment]
> Created the PR @arnaudlh but there is one conflict in the models_generated.go file. is this up to me to fix this?

Thanks for the PR @schoenr79, no worries I will resolve the conflict on test/merge.

Arnaud

**Review by arnaudlh — APPROVED** [review]
LGTM

**Comment by schoenr79** [comment]
Any Updates on that? Do we wait for the 2nd review @arnaudlh...

**Pull request merged**
